### ISSUE TITLE
Error with manually triggering the ML job

### ISSUE THREAD

**Issue by tapiatellez** [MicrosoftLearning/mslearn-mlops#14]
I modified the 02-manual-trigger-job.yml to manually trigger the ML job with the following commands: 
![Screen Shot 2022-11-18 at 23 23 56](https://user-images.githubusercontent.com/13044100/202835811-ba7afa45-7b23-47e0-bced-84d41d7199f0.png)
Everything seems to work fine but while manually triggering the action, I get the following error: 
![Screen Shot 2022-11-18 at 23 25 41](https://user-images.githubusercontent.com/13044100/202835863-c8582849-2c5b-40d0-b842-859edae97be0.png)
It seems that the triggering action, although coming from my GitHub account and loging into Azure as myself, does not contain the needed permissions to use the compute instance. Could you be so kind and help me with this?

Thanks in advance and hope to hear back from you soon, 

Cheers.

**Comment by madiepev** [comment]
Hi! Hints are provided in the challenges to help you. If you check the hint for this challenge, it'll tell you that GH is not authenticated to use the compute instance, only the compute cluster: 
![image](https://user-images.githubusercontent.com/48012580/203268814-746c4ecf-97e2-4dee-9087-305a1e518618.png)
