### ISSUE TITLE
code-checks throwing deprecated error causing inability to complete progress.

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/mslearn-mlops#17]
![image](https://user-images.githubusercontent.com/104829457/227380797-f581c015-fe78-4283-9513-3b8eb89ab98c.png)
Can you investigate and help me identify why the linting doesn't quite work when I manually trigger and where the set-output is triggering?. 

Error message

```
lintingProcess completed with exit code 1.
--
lintingThe `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The code check file: 

`name: Code checks

on:
  workflow_dispatch:
  pull_request:
      branches:
      - main

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/

`

**Comment by aastha44ma** [comment]
the pull request tag is not properly written
